on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'Dockerfile'

env:
  AMD64_RUNNER: ubuntu-latest
  ARM64_RUNNER: buildjet-2vcpu-ubuntu-2204-arm



jobs:

  example_matrix:
    strategy:
      matrix:
        os: [buildjet-2vcpu-ubuntu-2204-arm, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print Runner Information
        run: |
          if [[ "${{ runner.arch }}" == "X64" ]]; then
            echo "Runner is amd64"
            echo "PLATFORM=amd64" >> $GITHUB_ENV
          elif [[ "${{ runner.arch }}" == "ARM64" ]]; then
            echo "Runner is arm64"
            echo "PLATFORM=arm64" >> $GITHUB_ENV
          fi
      - name: matrix test
        run: |
            echo "PLATFORM=${{ env.PLATFORM }}"
        